DROP TABLE IF EXISTS helo_users;
DROP TABLE IF EXISTS helo_posts;

CREATE TABLE IF NOT EXISTS helo_users (id SERIAL PRIMARY KEY, username VARCHAR(40) NOT NULL, password VARCHAR(100) NOT NULL, profile_pic TEXT);
CREATE TABLE IF NOT EXISTS helo_posts (id SERIAL PRIMARY KEY, title VARCHAR(45) NOT NULL, content TEXT, img TEXT, author_id INTEGER, date_created TIMESTAMP);